# FLIGHT PRICE PREDICTION(EDA+FEATURE ENGINEERING)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df_train=pd.read_excel('Data_Train.xlsx')
df_train.head()

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897  
1    05:50         13:15   7h 25m     2 stops         No info   7662  
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882  
3    18:05         23:30   5h 25m      1 stop         No info   6218  
4    16:50         21:35   4h 45m      1 stop         No info  13302

In [4]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64 
dtypes: int64(1), object(10)
memory usage: 918.2+ KB


In [5]:
df_train.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [9]:
df_test=pd.read_excel('Test_set.xlsx')
df_test.head()
df_test.shape

(2671, 10)

In [11]:
final_df=df_train.append(df_test)
final_df.head()

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info    Price  
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897.0  
1    05:50         13:15   7h 25m     2 stops         No info   7662.0  
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882.0  
3    18:05         23:30   5h 25m      1 stop         No info   6218.0  
4    16:50         21:35   4h 45m      1 stop         No info  13302.0

In [14]:
##feature engineering process
final_df['Date_of_Journey'].str.split('/')

0       [24, 03, 2019]
1        [1, 05, 2019]
2        [9, 06, 2019]
3       [12, 05, 2019]
4       [01, 03, 2019]
             ...      
2666     [6, 06, 2019]
2667    [27, 03, 2019]
2668     [6, 03, 2019]
2669     [6, 03, 2019]
2670    [15, 06, 2019]
Name: Date_of_Journey, Length: 13354, dtype: object

In [15]:
final_df['Date']=final_df['Date_of_Journey'].str.split('/').str[0]
final_df['Month']=final_df['Date_of_Journey'].str.split('/').str[1]
final_df['Year']=final_df['Date_of_Journey'].str.split('/').str[2]

In [16]:
final_df.head()

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info    Price Date  \
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897.0   24   
1    05:50         13:15   7h 25m     2 stops         No info   7662.0    1   
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882.0    9   
3    18:05         23:30   5h 25m      1 stop         No info   6218.0   12   
4    16:50         21:35   4h 45m      1 stop         No info  13302.0   01   

  Month  Year  
0    03  2019  
1    05  2019  
2    06  2019  
3    05  2019  
4    03  2019

In [18]:
final_df['Date']=final_df['Date'].astype(int)
final_df['Month']=final_df['Date'].astype(int)
final_df['Year']=final_df['Year'].astype(int)

In [19]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Airline          13354 non-null  object 
 1   Date_of_Journey  13354 non-null  object 
 2   Source           13354 non-null  object 
 3   Destination      13354 non-null  object 
 4   Route            13353 non-null  object 
 5   Dep_Time         13354 non-null  object 
 6   Arrival_Time     13354 non-null  object 
 7   Duration         13354 non-null  object 
 8   Total_Stops      13353 non-null  object 
 9   Additional_Info  13354 non-null  object 
 10  Price            10683 non-null  float64
 11  Date             13354 non-null  int32  
 12  Month            13354 non-null  int32  
 13  Year             13354 non-null  int32  
dtypes: float64(1), int32(3), object(10)
memory usage: 1.6+ MB


In [21]:
final_df.drop(['Date_of_Journey'],axis=1,inplace=True)

In [22]:
final_df.head(1)

Airline    Source Destination      Route Dep_Time  Arrival_Time Duration  \
0  IndiGo  Banglore   New Delhi  BLR → DEL    22:20  01:10 22 Mar   2h 50m   

  Total_Stops Additional_Info   Price  Date  Month  Year  
0    non-stop         No info  3897.0    24     24  2019

In [23]:
final_df['Arrival_Time'].str.split(' ')

0       [01:10, 22, Mar]
1                [13:15]
2       [04:25, 10, Jun]
3                [23:30]
4                [21:35]
              ...       
2666    [20:25, 07, Jun]
2667             [16:55]
2668    [04:25, 07, Mar]
2669             [19:15]
2670             [19:15]
Name: Arrival_Time, Length: 13354, dtype: object

In [25]:
final_df['Arrival_Time']=final_df['Arrival_Time'].str.split(' ').str[0]

In [26]:
final_df.head(1)

Airline    Source Destination      Route Dep_Time Arrival_Time Duration  \
0  IndiGo  Banglore   New Delhi  BLR → DEL    22:20        01:10   2h 50m   

  Total_Stops Additional_Info   Price  Date  Month  Year  
0    non-stop         No info  3897.0    24     24  2019

In [27]:
final_df['Arrival_hour']=final_df['Arrival_Time'].str.split(':').str[0]
final_df['Arrival_min']=final_df['Arrival_Time'].str.split(':').str[1]

In [28]:
final_df.head(1)

Airline    Source Destination      Route Dep_Time Arrival_Time Duration  \
0  IndiGo  Banglore   New Delhi  BLR → DEL    22:20        01:10   2h 50m   

  Total_Stops Additional_Info   Price  Date  Month  Year Arrival_hour  \
0    non-stop         No info  3897.0    24     24  2019           01   

  Arrival_min  
0          10

In [29]:
final_df['Arrival_hour']=final_df['Arrival_hour'].astype(int)
final_df['Arrival_min']=final_df['Arrival_min'].astype(int)

In [30]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Airline          13354 non-null  object 
 1   Source           13354 non-null  object 
 2   Destination      13354 non-null  object 
 3   Route            13353 non-null  object 
 4   Dep_Time         13354 non-null  object 
 5   Arrival_Time     13354 non-null  object 
 6   Duration         13354 non-null  object 
 7   Total_Stops      13353 non-null  object 
 8   Additional_Info  13354 non-null  object 
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  int32  
 11  Month            13354 non-null  int32  
 12  Year             13354 non-null  int32  
 13  Arrival_hour     13354 non-null  int32  
 14  Arrival_min      13354 non-null  int32  
dtypes: float64(1), int32(5), object(9)
memory usage: 1.6+ MB


In [32]:
final_df.drop(['Arrival_Time'],axis=1,inplace=True)

In [34]:
final_df.head(1)

Airline    Source Destination      Route Dep_Time Duration Total_Stops  \
0  IndiGo  Banglore   New Delhi  BLR → DEL    22:20   2h 50m    non-stop   

  Additional_Info   Price  Date  Month  Year  Arrival_hour  Arrival_min  
0         No info  3897.0    24     24  2019             1           10

In [39]:
final_df['Dep_hour']=final_df['Dep_Time'].str.split(':').str[0]
final_df['Dep_min']=final_df['Dep_Time'].str.split(':').str[1]
final_df['Dep_hour']=final_df['Dep_hour'].astype(int)
final_df['Dep_min']=final_df['Dep_min'].astype(int)

In [37]:
final_df.head(1)

Airline    Source Destination      Route Dep_Time Duration Total_Stops  \
0  IndiGo  Banglore   New Delhi  BLR → DEL    22:20   2h 50m    non-stop   

  Additional_Info   Price  Date  Month  Year  Arrival_hour  Arrival_min  \
0         No info  3897.0    24     24  2019             1           10   

  Dep_hour Dep_min  
0       22      20

In [40]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Airline          13354 non-null  object 
 1   Source           13354 non-null  object 
 2   Destination      13354 non-null  object 
 3   Route            13353 non-null  object 
 4   Dep_Time         13354 non-null  object 
 5   Duration         13354 non-null  object 
 6   Total_Stops      13353 non-null  object 
 7   Additional_Info  13354 non-null  object 
 8   Price            10683 non-null  float64
 9   Date             13354 non-null  int32  
 10  Month            13354 non-null  int32  
 11  Year             13354 non-null  int32  
 12  Arrival_hour     13354 non-null  int32  
 13  Arrival_min      13354 non-null  int32  
 14  Dep_hour         13354 non-null  int32  
 15  Dep_min          13354 non-null  int32  
dtypes: float64(1), int32(7), object(8)
memory usage: 1.6+ MB


In [41]:
final_df.drop(['Dep_Time'],axis=1,inplace=True)

In [43]:
final_df.head(1)

Airline    Source Destination      Route Duration Total_Stops  \
0  IndiGo  Banglore   New Delhi  BLR → DEL   2h 50m    non-stop   

  Additional_Info   Price  Date  Month  Year  Arrival_hour  Arrival_min  \
0         No info  3897.0    24     24  2019             1           10   

   Dep_hour  Dep_min  
0        22       20

In [46]:
final_df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [47]:
final_df['Total_Stops']=final_df['Total_Stops'].map({'non-stop':0,'1 stop':1,'2 stops':2,'3 stops':3,'4 stops':4,'nan':1})

In [48]:
final_df['Total_Stops']

0       0.0
1       2.0
2       2.0
3       1.0
4       1.0
       ... 
2666    1.0
2667    0.0
2668    1.0
2669    1.0
2670    1.0
Name: Total_Stops, Length: 13354, dtype: float64

In [49]:
final_df.drop(['Route'],axis=1,inplace=True)

In [50]:
final_df.head(1)

Airline    Source Destination Duration  Total_Stops Additional_Info   Price  \
0  IndiGo  Banglore   New Delhi   2h 50m          0.0         No info  3897.0   

   Date  Month  Year  Arrival_hour  Arrival_min  Dep_hour  Dep_min  
0    24     24  2019             1           10        22       20

In [51]:
final_df['Duration']=final_df['Duration'].str.split(" ").str[0]

In [52]:
final_df.head(1)

Airline    Source Destination Duration  Total_Stops Additional_Info   Price  \
0  IndiGo  Banglore   New Delhi       2h          0.0         No info  3897.0   

   Date  Month  Year  Arrival_hour  Arrival_min  Dep_hour  Dep_min  
0    24     24  2019             1           10        22       20

In [54]:
final_df['Duration_hour']=final_df['Duration'].str.split(" ").str[0].str.split('h').str[0]

In [55]:
final_df.head(1)

Airline    Source Destination Duration  Total_Stops Additional_Info   Price  \
0  IndiGo  Banglore   New Delhi       2h          0.0         No info  3897.0   

   Date  Month  Year  Arrival_hour  Arrival_min  Dep_hour  Dep_min  \
0    24     24  2019             1           10        22       20   

  Duration_hour  
0             2

In [61]:
final_df['Duration_hour']=final_df['Duration_hour'].astype(int)

In [60]:
final_df[final_df['Duration_hour']=='5m']

Empty DataFrame
Columns: [Airline, Source, Destination, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, Arrival_hour, Arrival_min, Dep_hour, Dep_min, Duration_hour]
Index: []

In [59]:
final_df.drop(6474,axis=0,inplace=True)
final_df.drop(2660,axis=0,inplace=True)

In [63]:
final_df.drop(['Duration'],axis=1,inplace=True)

In [65]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()

In [68]:
final_df['Airline']=labelencoder.fit_transform(final_df['Airline'])
final_df['Source']=labelencoder.fit_transform(final_df['Source'])
final_df['Destination']=labelencoder.fit_transform(final_df['Destination'])
final_df['Additional_Info']=labelencoder.fit_transform(final_df['Additional_Info'])

In [70]:
final_df['Airline'].unique()

array([ 3,  1,  4,  8,  6,  2, 10,  0, 11,  5,  7,  9], dtype=int64)

In [72]:
final_df['Source'].unique()

array([0, 3, 2, 1, 4], dtype=int64)

In [73]:
final_df['Destination'].unique()

array([5, 0, 1, 4, 2, 3], dtype=int64)

In [75]:
final_df['Additional_Info'].unique()

array([8, 5, 7, 1, 6, 0, 4, 3, 9, 2])